---
name: Publish to Docker Hub
on:
  push:
    branches:
      - main
#   # Publish master every Thursday at 7AM (schedule only applies to the master branch)
#   schedule:
#     - cron: "0 12 * * 2"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Get datetime for tag
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY-MM-DDTHHmmSS

      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: dhrn
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: dhrn/dhcp-netboot.xyz
          tags: latest, ${{ steps.current-time.outputs.formattedTime }}

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: dhrn
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
          DOCKERHUB_REPOSITORY: dhrn/dhcp-netboot.xyz
